services:
  mysql:
    image: mysql
    container_name: mysql_compose
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - employee_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - employee_network
    depends_on:
      - mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile # optional if your Dockerfile is named 'Dockerfile'
    image: employee_management_image
    container_name: employee_management_app
    ports:
      - "9493:8080"
    networks:
      - employee_network
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
networks:
  employee_network:
    driver: bridge